### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by joseym** [pegli/couchbase_ti#11]
I've downloaded 1.0.3 but when I attempt to build i a test app I get the following error:

```
[ERROR] Error: Traceback (most recent call last):
File "/Users/jmorton/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1274, in main
execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=__LOG__ID__=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s %s" % (log_id,sdk_version,debugstr,kroll_coverage)],False)
File "/Users/jmorton/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1180, in execute_xcode
output = run.run(args,False,False,o)
File "/Users/jmorton/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/run.py", line 39, in run
sys.exit(rc)
SystemExit: 65
```

**Comment by pegli** [comment]
Any time you see an "Error 65" with a build, it means that the Titanium build script failed for some reason. Open up the build/iphone/build/build.log file and scroll to the end to find the error.  If it isn't something obvious, please post the last 20-30 lines into this issue report.

**Comment by joseym** [comment]
You're right. It didn't like that my project name started with CouchDB.

Was able to get past that error but now this error has returned:

```
[ERROR] Script Error = Couldn't find module: com.obscure.couchbase_ti.
```

On Sat, Jan 21, 2012 at 12:43 PM, Paul Mietz Egli <
reply@reply.github.com

**Comment by Josh-Miller** [comment]
Hmm I seem to be having the same problem.

[ERROR] Script Error = Couldn't find module: com.obscure.couchbase_ti.

**Comment by pegli** [comment]
In version 1.1, I changed the name of the module because Android wouldn't build when I had an underscore in the module name.  The new name is "com.obscure.CouchbaseTi".  Can you take a look at the wiki (https://github.com/pegli/couchbase_ti/wiki) to make sure your tiapp.xml file and code matches the instructions on the home page?  If your files are correct, you might try deleting and reinstalling the module from ~/Library/Application Support/Titanium.
